pull_request_rules:
  - name: automatic merge for master when CI passes and 1 review and not manual merge tag
    conditions:
      - "#approved-reviews-by>=0"
      - check-success=build (3.8)
      - check-success=execute-mysql-queries (3.8)
      - base=master
      - label!=manual
    actions:
      merge:
        method: rebase
